### ISSUE TITLE
Any sample_transaction record on testNet?

### ISSUE THREAD

**Issue by hisunwei** [sekai-studio/paymaster#3]
Hello, I succeeded in declaring and deploying the contract, but the sample transaction failed with the following error:

`[Paymaster] Starting transfer.
Traceback (most recent call last):
  File "examples/transaction/sample_transaction.py", line 118, in <module>
    asyncio.run(main())
  File "/Users/user/.pyenv/versions/3.8.9/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/user/.pyenv/versions/3.8.9/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "examples/transaction/sample_transaction.py", line 113, in main
    await payer_account.client.wait_for_tx(transfer_paid.transaction_hash)
  File "/Users/user/.pyenv/versions/cairo/lib/python3.8/site-packages/starknet_py/net/client.py", line 159, in wait_for_tx
    raise TransactionRejectedError(
starknet_py.transaction_exceptions.TransactionRejectedError: Transaction was rejected with following starknet error: Error at pc=0:12:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:161)
Unknown location (pc=0:147)

Error in the called contract (0x10364bdceef999e5d31010b77da996ab821bc3d48b1f3d2340733ce6cbcbe6d):
Error at pc=0:39:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:1398)
Unknown location (pc=0:1351)
Unknown location (pc=0:569)
Error message: argent: multicall 0 failed
Unknown location (pc=0:586)

Error in the called contract (0x6edad3401692041efc2158c2ab2e4e6cb82e9c0b507495720dc584d8d1ceee6):
Error at pc=0:12:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:161)
Unknown location (pc=0:147)

Error in the called contract (0x6edad3401692041efc2158c2ab2e4e6cb82e9c0b507495720dc584d8d1ceee6):
Entry point 0x13191c98b3d11291b45e74659aa39d08d350d3f84c44724c03816269e78c4c7 not found in contract with class hash 0x33434ad846cdd5f23eb73ff09fe6fddd568284a0fb7d1be20ee482f044dabe2..`

my .env is below

`
PAYER_ADDRESS = 0x010364bdceef999E5d31010B77Da996aB821Bc3d48B1F3D2340733ce6cbcbe6D
PAYER_PRIVATE_KEY =xxxx

USER_ADDRESS = 0x06Edad3401692041eFC2158C2AB2e4E6cB82e9C0B507495720DC584D8D1cEee6
USER_PRIVATE_KEY =xxx

ETH_TOKEN_ADDRESS = 0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
RECIPIENT_ADDRESS = 0x062e5Cd6dc105cf3DCc3921EEFDD3bae1134DE6C884A47c121fB453fD9784e42

`

deploy contract here: 
https://testnet.starkscan.co/contract/0x04cc39fe4d2636c808ab94d0303b1c0c011acdc5594adb76269954ece3a1615d#overview
declare here:
https://testnet.starkscan.co/tx/0x056c97caece0678d82e383598b82567532bc46ba35e39f9753572f874c34371d

Can you help point out my problem? Or any sample_transaction record on testNet?

**Comment by hisunwei** [comment]
Resolved
